### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by hollenberry** [githubschool/march-19#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by brianamarie** [comment]
I know the basics of being an admin but I want to see how to do the important stuff

**Comment by allthedoll** [comment]
![spring corgi](https://media.giphy.com/media/gB4KWtd3uSsJq/giphy.gif)

**Comment by hollenberry** [comment]
What do you already know about using and administrating GitHub? What would you like to learn?

**Comment by IAmHughes** [comment]
![fun-stuff](https://media1.tenor.com/images/b756ad2cd7dceb7c8ad787a61c82d43f/tenor.gif?itemid=12844669)

I also want to learn to:

![just-do-it](https://media1.tenor.com/images/7cd63e804a14789acef74bc1918f7a08/tenor.gif?itemid=4531935)

I'd like to learn about GitHub's permission models

**Comment by beardofedu** [comment]
I know how to make teams.
I want to learn how to require protected branches in repositories.
